apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediconnect.fullname" . }}-config
data:
  APP_ENV: "{{ .Values.environment }}"
  APP_DOMAIN: "{{ .Values.ingress.hostname }}"
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
