apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediconnect.fullname" . }}-api
  labels:
    app: {{ include "mediconnect.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "mediconnect.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mediconnect.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: reverb
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "mediconnect.fullname" . }}-config
            # In a real Medical prod, use SealedSecrets for sensitive variables
            - secretRef:
                name: {{ include "mediconnect.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /up
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /up
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000 # maps to the laravel user
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
